#!/usr/bin/env sh

set -e

if [ ! -d "$1" ]; then
    echo "Usage: $0 <folder>"
    exit 1
fi

find "$1" -type f -name "*.d" | while read -r f; do
    echo "Processing: $f"
    sed -E \
        -e 's/^(module[[:space:]]+)parin\./\1/' \
        -e 's/^(import[[:space:]]+)parin\./\1/' \
        -e 's/^(import[[:space:]]+[[:alnum:]_]+[[:space:]]*=[[:space:]]*)parin\./\1/' \
        "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done
