#!/bin/env sh

## I am too lazy to remember these commands.

set -xe
ls examples/*.d | xargs -I xx dmd -i -of=.temp -I=source -J=source/joka -run xx
dmd -i -of=.temp -I=source -J=source/joka -run ./examples/_008_cli.d one two -a --foo
