#!/bin/env sh
set -e

## A WASM-4 project should look like this:
##    +- Folder -+
##    | app.d    |
##    | joka     |
##    | w4run    |
##    +----------+

output="app.wasm"
 files="app.d"
extras=""

cd "$(dirname "$0")"
ldc2 -of=$output             \
    $files $extras           \
    -i -betterC              \
    --mtriple=wasm32         \
    --checkaction=halt       \
    -L--export=update        \
    -L--allow-undefined      \
    -L--no-entry             \
    -L--stack-first          \
    -L--import-memory        \
    -L--initial-memory=65536 \
    -L--max-memory=65536     \
    -L-zstack-size=14752     \

rm *.o
w4 run-native "$output"
